name: enr_tickets
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  awesome_dialog: ^3.3.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  share_plus: ^7.2.1
  qr_flutter: ^4.1.0
  flutter_bloc: ^9.1.1
  gap: ^3.0.1
  intl: ^0.20.2
  pdf: ^3.10.4
  printing: ^5.12.0
  
  webview_flutter: ^4.0.7

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/   # 🔥 مهم جدًا (مش ملف واحد)

  fonts:
  - family: HelveticaWorld
    fonts:
     
      - asset: assets/fonts/HelveticaWorld-Regular.ttf
        weight: 700

  - family: Amiri
    fonts:
      - asset: assets/fonts/Amiri-Regular.ttf